spring:
  main:
    banner-mode: off
  r2dbc:
    initialization-mode: always
    url: r2dbc:h2:mem:///testdb?options=DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
logging:
  level:
    io.r2dbc.h2: TRACE
